# Generated by Django 6.0.5 on 2026-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_add_card_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='target',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text="Admin-set deposit target shown as a progress bar on the user's portfolio page.", max_digits=20, verbose_name='Deposit Target'),
        ),
    ]
