# Generated by Django 6.0.5 on 2026-07-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_news_fmp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='external_image_url',
            field=models.URLField(blank=True, default='', help_text='Image URL from external source (e.g. FMP). Used when no Cloudinary image is uploaded.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Original article URL. Used for deduplication when syncing from FMP.'),
        ),
    ]
