# Generated by Django 6.0.5 on 2026-07-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_stock_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='app_stock_categor_c950a0_idx',
            old_name='app_stock_category_idx',
        ),
    ]
